name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Membuat direktori dist
      - name: Create dist directory
        run: mkdir -p dist

      # Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: yudhaislamisulistya
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Pastikan file SVG yang dihasilkan ada
      - name: Check SVG File
        run: test -f dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
